"""Initial schema

Revision ID: b06e5797e877
# Revises: 
Create Date: 2025-05-23 10:43:03.635338

print(f"Starting migration: b06e5797e877")

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06e5797e877'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    print("Applying Alembic revision b06e5797e877...")

    op.create_table(
        "videos",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Enum("pending", "downloading", "downloaded"), default="pending", nullable=False),

        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),

        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subtitles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column("status", sa.Enum("pending", "translating", "translated"), default="pending", nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),

        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ),
        
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
    # pass
    # ### end Alembic commands ###
