name: Deploy Subtitle Translator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: "production"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Ensure pip cache exists
        run: mkdir -p ~/.cache/pip

      - name: Deploy Subtitle Translator
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            echo "--- setting up known_hosts ---"
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            echo "--- checking repo ---"
            if [ ! -d /home/subtitle_translator ]; then
              echo "Cloning repo..."
              git clone git@github.com:alitak/subtitle-translator-core.git /home/subtitle_translator
            fi

            echo "Repo ready. Pulling latest..."
            cd /home/subtitle_translator
            git pull origin main

            echo "--- installing dependencies ---"
            python3 -m pip install --upgrade pip
            pip install .

            echo "--- writing .env ---"
            cat > .env << EOL
            BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}
            BINANCE_SECRET_KEY=${{ secrets.BINANCE_SECRET_KEY }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            WALLET_ENDPOINT=${{ secrets.WALLET_ENDPOINT }}
            EOL

            echo "--- creating logs dir ---"
            mkdir -p logs

            echo "--- restarting bot screen ---"
            screen -S subtitle_translator -X quit || true
            screen -dmS subtitle_translator python3 /home/subtitle_translator/main.py
